### PR TITLE
Messages editing

### LINKED ISSUE #3: WS reconnect failed
Currently, after connection was broken, we trying to reconnect using recursive function with timeout, which doesn't work properly.

### LINKED ISSUE #5: ResizableTextarea doesn't reset rows count on submit

### PR DESCRIPTION
**Pull request by mrprfrm**
Messages edit functions.
---
#5 #3

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -1,12 +1,11 @@
 /* eslint-disable import/prefer-default-export */
+import ReconnectingWebSocket from 'reconnecting-websocket';
+
 export function connectToBrocker(brokerUrl, store, delay = 1000) {
```
Comment (mrprfrm) [inline src/utils.js]: Remove redundant arguments.

**Review by mrprfrm — COMMENTED** [review]
Looks ok

**Review by kuzminivan — APPROVED** [review]
@mrprfrm Everything is ok
